version: '3'
services:

  server:
    build: ./
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MODE: release
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: companies
      DB_HOST: database
      DB_PORT: 5432

  database:
    image: jorgenringen/ms_samples_postgres
    ports:
      - 5432:5432
